from http import HTTPStatus

SUCCESS = HTTPStatus.OK
CREATED = HTTPStatus.CREATED
UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
FORBIDDEN = HTTPStatus.FORBIDDEN
BAD_REQUEST = HTTPStatus.BAD_REQUEST
NOT_FOUND = HTTPStatus.NOT_FOUND
INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR